name: Build

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build C++
        container:
          image: rootproject/root:latest
        run: |
          cd cpp/src
          make

      - name: Build Python
        run: |
          cd python
          python3 -m pip install .

